/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-27 at 06:50:51 UTC 
 * Modify at your own risk.
 */

package com.appspot.specialkidinfo.specialkidinfoapi;

/**
 * Service definition for Specialkidinfoapi (v1).
 *
 * <p>
 * An API for managing special kids info
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link com.appspot.specialkidinfo.specialkidinfoapi.SpecialkidinfoapiRequestInitializer} to initialize global parameters via its
 * {@link com.appspot.specialkidinfo.specialkidinfoapi.Specialkidinfoapi.Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Specialkidinfoapi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the specialkidinfoapi library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://specialkidinfo.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "specialkidinfoapi/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link com.appspot.specialkidinfo.specialkidinfoapi.Specialkidinfoapi.Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Specialkidinfoapi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Specialkidinfoapi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getAllProviders".
   *
   * This request holds the parameters needed by the specialkidinfoapi server.  After setting any
   * optional parameters, call the {@link com.appspot.specialkidinfo.specialkidinfoapi.Specialkidinfoapi.GetAllProviders#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public GetAllProviders getAllProviders() throws java.io.IOException {
    GetAllProviders result = new GetAllProviders();
    initialize(result);
    return result;
  }

  public class GetAllProviders extends SpecialkidinfoapiRequest<com.appspot.specialkidinfo.specialkidinfoapi.model.ServiceProviderCollection> {

    private static final String REST_PATH = "serviceprovidercollection";

    /**
     * Create a request for the method "getAllProviders".
     *
     * This request holds the parameters needed by the the specialkidinfoapi server.  After setting
     * any optional parameters, call the {@link com.appspot.specialkidinfo.specialkidinfoapi.Specialkidinfoapi.GetAllProviders#execute()} method to invoke the remote
     * operation. <p> {@link com.appspot.specialkidinfo.specialkidinfoapi.Specialkidinfoapi.GetAllProviders#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected GetAllProviders() {
      super(Specialkidinfoapi.this, "GET", REST_PATH, null, com.appspot.specialkidinfo.specialkidinfoapi.model.ServiceProviderCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAllProviders setAlt(String alt) {
      return (GetAllProviders) super.setAlt(alt);
    }

    @Override
    public GetAllProviders setFields(String fields) {
      return (GetAllProviders) super.setFields(fields);
    }

    @Override
    public GetAllProviders setKey(String key) {
      return (GetAllProviders) super.setKey(key);
    }

    @Override
    public GetAllProviders setOauthToken(String oauthToken) {
      return (GetAllProviders) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAllProviders setPrettyPrint(Boolean prettyPrint) {
      return (GetAllProviders) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAllProviders setQuotaUser(String quotaUser) {
      return (GetAllProviders) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAllProviders setUserIp(String userIp) {
      return (GetAllProviders) super.setUserIp(userIp);
    }

    @Override
    public GetAllProviders set(String parameterName, Object value) {
      return (GetAllProviders) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getProvider".
   *
   * This request holds the parameters needed by the specialkidinfoapi server.  After setting any
   * optional parameters, call the {@link com.appspot.specialkidinfo.specialkidinfoapi.Specialkidinfoapi.GetProvider#execute()} method to invoke the remote
   * operation.
   *
   * @param type
   * @return the request
   */
  public GetProvider getProvider(String type) throws java.io.IOException {
    GetProvider result = new GetProvider(type);
    initialize(result);
    return result;
  }

  public class GetProvider extends SpecialkidinfoapiRequest<com.appspot.specialkidinfo.specialkidinfoapi.model.ServiceProvider> {

    private static final String REST_PATH = "serviceprovider/{type}";

    /**
     * Create a request for the method "getProvider".
     *
     * This request holds the parameters needed by the the specialkidinfoapi server.  After setting
     * any optional parameters, call the {@link com.appspot.specialkidinfo.specialkidinfoapi.Specialkidinfoapi.GetProvider#execute()} method to invoke the remote
     * operation. <p> {@link
     * com.appspot.specialkidinfo.specialkidinfoapi.Specialkidinfoapi.GetProvider#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param type
     * @since 1.13
     */
    protected GetProvider(String type) {
      super(Specialkidinfoapi.this, "GET", REST_PATH, null, com.appspot.specialkidinfo.specialkidinfoapi.model.ServiceProvider.class);
      this.type = com.google.api.client.util.Preconditions.checkNotNull(type, "Required parameter type must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetProvider setAlt(String alt) {
      return (GetProvider) super.setAlt(alt);
    }

    @Override
    public GetProvider setFields(String fields) {
      return (GetProvider) super.setFields(fields);
    }

    @Override
    public GetProvider setKey(String key) {
      return (GetProvider) super.setKey(key);
    }

    @Override
    public GetProvider setOauthToken(String oauthToken) {
      return (GetProvider) super.setOauthToken(oauthToken);
    }

    @Override
    public GetProvider setPrettyPrint(Boolean prettyPrint) {
      return (GetProvider) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetProvider setQuotaUser(String quotaUser) {
      return (GetProvider) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetProvider setUserIp(String userIp) {
      return (GetProvider) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private String type;

    /**

     */
    public String getType() {
      return type;
    }

    public GetProvider setType(String type) {
      this.type = type;
      return this;
    }

    @Override
    public GetProvider set(String parameterName, Object value) {
      return (GetProvider) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link com.appspot.specialkidinfo.specialkidinfoapi.Specialkidinfoapi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link com.appspot.specialkidinfo.specialkidinfoapi.Specialkidinfoapi}. */
    @Override
    public Specialkidinfoapi build() {
      return new Specialkidinfoapi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link com.appspot.specialkidinfo.specialkidinfoapi.SpecialkidinfoapiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setSpecialkidinfoapiRequestInitializer(
        SpecialkidinfoapiRequestInitializer specialkidinfoapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(specialkidinfoapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
