/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-02-27 at 11:32:26 UTC 
 * Modify at your own risk.
 */

package com.appspot.specialkidinfo.specialkidinfoapi.model;

/**
 * Model definition for ServiceProvider.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the specialkidinfoapi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ServiceProvider extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String address;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String emailAddress;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String landlineNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String location;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String mobileNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String remark;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String sublocation;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String type;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String website;

  /**
   * @return value or {@code null} for none
   */
  public String getAddress() {
    return address;
  }

  /**
   * @param address address or {@code null} for none
   */
  public ServiceProvider setAddress(String address) {
    this.address = address;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getEmailAddress() {
    return emailAddress;
  }

  /**
   * @param emailAddress emailAddress or {@code null} for none
   */
  public ServiceProvider setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getLandlineNumber() {
    return landlineNumber;
  }

  /**
   * @param landlineNumber landlineNumber or {@code null} for none
   */
  public ServiceProvider setLandlineNumber(String landlineNumber) {
    this.landlineNumber = landlineNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getLocation() {
    return location;
  }

  /**
   * @param location location or {@code null} for none
   */
  public ServiceProvider setLocation(String location) {
    this.location = location;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getMobileNumber() {
    return mobileNumber;
  }

  /**
   * @param mobileNumber mobileNumber or {@code null} for none
   */
  public ServiceProvider setMobileNumber(String mobileNumber) {
    this.mobileNumber = mobileNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public ServiceProvider setName(String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getRemark() {
    return remark;
  }

  /**
   * @param remark remark or {@code null} for none
   */
  public ServiceProvider setRemark(String remark) {
    this.remark = remark;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getSublocation() {
    return sublocation;
  }

  /**
   * @param sublocation sublocation or {@code null} for none
   */
  public ServiceProvider setSublocation(String sublocation) {
    this.sublocation = sublocation;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getType() {
    return type;
  }

  /**
   * @param type type or {@code null} for none
   */
  public ServiceProvider setType(String type) {
    this.type = type;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getWebsite() {
    return website;
  }

  /**
   * @param website website or {@code null} for none
   */
  public ServiceProvider setWebsite(String website) {
    this.website = website;
    return this;
  }

  @Override
  public ServiceProvider set(String fieldName, Object value) {
    return (ServiceProvider) super.set(fieldName, value);
  }

  @Override
  public ServiceProvider clone() {
    return (ServiceProvider) super.clone();
  }

}
